from .akinator_dc import AkinatorDiscord
from .blackjack_dc import BlackjackDiscord
from .chess_dc import ChessDiscord
from .connect4_dc import Connect4Discord
from .flood_dc import FloodDiscord
from .hangman_dc import HangmanDiscord
from .mastermind_dc import MastermindDiscord
from .quiz_dc import QuizDiscord
from .scramble_dc import ScrambleDiscord
