from .developer.clear import ClearCommand
from .developer.delete import DeleteCommand
from .developer.restart import RestartCommand
from .developer.say import SayCommand
from .developer.temperature import TemperatureCommand
from .developer.xec import ExecuteCommand
from .minigames.hangman_cmd import HangmanCommand
from .minigames.scramble_cmd import ScrambleCommand
from .miscellaneous.help import HelpCommand
from .miscellaneous.info import InfoCommand
from .miscellaneous.rules import RulesCommand
